name: robot_control_center
description: A control center app for personal robot
publish_to: 'codejapoe'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  audioplayers: ^5.2.1
  speech_to_text: ^7.0.0
  google_generative_ai: ^0.2.0
  permission_handler: ^11.1.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Frame 1.svg 
    - .env 